### ISSUE TITLE
Complete API Documentation

### ISSUE THREAD

**Issue by mcdonnelldean** [senecajs/senecajs.org#65] opened 2015-10-05 11:45 UTC
We are missing summaries for all methods in the API doc. We need to get this completed as soon as possible even just enough to round out what is there.

**Comment by AdrieanKhisbe** [comment] 2015-11-26 14:50
(@mcdonnelldean: is the trello board private to the development team, or is it possible to join it?)

**Comment by paolochiodi** [comment] 2015-11-26 14:54
The Trello board was private, but has been closed and all the discussion is happening in public (issue tracker or gitter chat). 
The original card didn't have any additional info.

I'm working on this, let me know if you have any suggestion or if you'd like to help

**Comment by AdrieanKhisbe** [comment] 2015-11-26 15:07
Okey Dokey,

I won't hesitate to give you any suggestion.
I'm currently building a POC using seneca to learn it, and check if it fits my team needs. (I totaly does for me :))
I'll give a hand with pleasure, but unsure I'll be that timesaving for you since I'm still new to seneca.
At least I can give you feedback on the Doc you are writing

**Comment by mcdonnelldean** [comment] 2015-11-26 15:55
It's public as far as I know. @geek ?

Kindest Regards,

Dean

**Comment by AdrieanKhisbe** [comment] 2015-11-27 14:57
Unfortunately no,  I get a :

> Card not found.
> 
> This card may be on a private board. If someone gave you this link, they may need to invite you to one of their boards or teams.`

**Comment by AdrieanKhisbe** [comment] 2015-12-03 11:43
@rjrodger @geek @mcdonnelldean  :question: 

_sorry to mention you to revive the discussion_ :smiley:

**Comment by mcdonnelldean** [comment] 2015-12-03 13:15
@AdrieanKhisbe Sorry about this. The board should be public. Let me ping @geek When he gets on and sort it out.

**Comment by AdrieanKhisbe** [comment] 2015-12-03 13:18
Don't be @mcdonnelldean :smiley:

**Comment by geek** [comment] 2015-12-03 15:09
That linked to an old board, here is the current one: https://trello.com/b/CHOb0esy/seneca-release-0-8

We switched gears, so we are creating cards that don't necessarily relate to a single github issue.

**Comment by AdrieanKhisbe** [comment] 2015-12-03 15:21
Huge thanks @geek :)
If i'm right you are using the column as sprint, and label as status. (todo, inprogress, done)

where can I find the documentation of a card action:
for instance https://trello.com/c/4OcHNJPj/47-add-support-in-sentinel-for-hapi-chairo-projects
didin't found any mention to `Sentinel` in `Chairo`

**Comment by geek** [comment] 2015-12-03 16:02
ahh, ya... sometimes they are bigger tasks that may span a few projects where there aren't issues setup.  For that task, the issue is here: https://github.com/senecajs/seneca-sentinel/issues/9

**Comment by AdrieanKhisbe** [comment] 2016-01-25 17:56
@senecajs/core  With awesome work of @kamil-mech, shall we close the issue or no?

**Closed** 2016-01-31 23:05 UTC
Labels: content
